"""Top-level package for vfa."""

__title__ = "vfa"
__description__ = "VFA: Vecor Field Attention"
__url__ = "https://github.com/yihao6/vfa"
__author__ = """Yihao Liu"""
__email__ = "yliu236@jhu.edu"
__version__ = "1.1.2"
__license__ = "GPLv3"
__copyright__ = "Copyright 2023 Yihao Liu"
